// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUsWRdPNNn16Q-qjpe20j_n2gUx4lyRXQ',
    appId: '1:743874364936:web:8cbc95387dd6cbab5d33bd',
    messagingSenderId: '743874364936',
    projectId: 'live-location-project-b0dcf',
    authDomain: 'live-location-project-b0dcf.firebaseapp.com',
    storageBucket: 'live-location-project-b0dcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlywYT8ME4lBnfZ6UBsHaPVIlHpUzm0eA',
    appId: '1:743874364936:android:e1dc6047bfc7714b5d33bd',
    messagingSenderId: '743874364936',
    projectId: 'live-location-project-b0dcf',
    storageBucket: 'live-location-project-b0dcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj2MEamW9fVIQCgCoGVyUW4LlJb0CjHgY',
    appId: '1:743874364936:ios:ed8031b3a60416be5d33bd',
    messagingSenderId: '743874364936',
    projectId: 'live-location-project-b0dcf',
    storageBucket: 'live-location-project-b0dcf.firebasestorage.app',
    iosBundleId: 'com.example.liveTrackingProject',
  );
}
